<?php
require_once './vendor/autoload.php';


$a = new \pagopa\crawler\events\req\nodoInviaCarrelloRPT([
    "insertedtimestamp" =>  "2024-03-13 09:10:00.210",
    "tipoEvento" =>  "nodoInviaCarrelloRPT",
    "sottoTipoEvento" =>  "REQ",
    "idDominio" =>  "",
    "iuv" =>  "",
    "ccp" =>  "",
    "noticeNumber" =>  "",
    "creditorReferenceId" =>  "",
    "paymentToken" =>  "",
    "psp" =>  "AGID_01",
    "stazione" =>  "77777777777_01",
    "canale" =>  "88888888888_01",
    "sessionId" =>  "SESSID_01",
    "sessionIdOriginal" =>  "SESSORIGIN_01",
    "uniqueId" =>  "UNIQUE_RPT_1",
    "payload" => "PHNvYXA6RW52ZWxvcGUgeG1sbnM6c29hcD0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhtbG5zOnhzZD0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiPgogIDxzb2FwOkhlYWRlcj4KICAgIDxpbnRlc3RhemlvbmVDYXJyZWxsb1BQVCB4bWxucz0iaHR0cDovL3dzLnBhZ2FtZW50aS50ZWxlbWF0aWNpLmdvdi9wcHRoZWFkIj4KICAgICAgPGlkZW50aWZpY2F0aXZvSW50ZXJtZWRpYXJpb1BBIHhtbG5zPSIiPjc3Nzc3Nzc3Nzc3PC9pZGVudGlmaWNhdGl2b0ludGVybWVkaWFyaW9QQT4KICAgICAgPGlkZW50aWZpY2F0aXZvU3RhemlvbmVJbnRlcm1lZGlhcmlvUEEgeG1sbnM9IiI+Nzc3Nzc3Nzc3NzdfMDE8L2lkZW50aWZpY2F0aXZvU3RhemlvbmVJbnRlcm1lZGlhcmlvUEE+CiAgICAgIDxpZGVudGlmaWNhdGl2b0NhcnJlbGxvIHhtbG5zPSIiPklEX0NBUlJFTExPXzAxPC9pZGVudGlmaWNhdGl2b0NhcnJlbGxvPgogICAgPC9pbnRlc3RhemlvbmVDYXJyZWxsb1BQVD4KICA8L3NvYXA6SGVhZGVyPgogIDxzb2FwOkJvZHk+CiAgICA8bm9kb0ludmlhQ2FycmVsbG9SUFQgeG1sbnM9Imh0dHA6Ly93cy5wYWdhbWVudGkudGVsZW1hdGljaS5nb3YvIj4KICAgICAgPHBhc3N3b3JkIHhtbG5zPSIiPlBMQUNFSE9MREVSPC9wYXNzd29yZD4KICAgICAgPGlkZW50aWZpY2F0aXZvUFNQIHhtbG5zPSIiPkFHSURfMDE8L2lkZW50aWZpY2F0aXZvUFNQPgogICAgICA8aWRlbnRpZmljYXRpdm9JbnRlcm1lZGlhcmlvUFNQIHhtbG5zPSIiPjg4ODg4ODg4ODg4PC9pZGVudGlmaWNhdGl2b0ludGVybWVkaWFyaW9QU1A+CiAgICAgIDxpZGVudGlmaWNhdGl2b0NhbmFsZSB4bWxucz0iIj44ODg4ODg4ODg4OF8wMTwvaWRlbnRpZmljYXRpdm9DYW5hbGU+CiAgICAgIDxsaXN0YVJQVCB4bWxucz0iIj4KICAgICAgICA8ZWxlbWVudG9MaXN0YVJQVD4KICAgICAgICAgIDxpZGVudGlmaWNhdGl2b0RvbWluaW8+Nzc3Nzc3Nzc3Nzc8L2lkZW50aWZpY2F0aXZvRG9taW5pbz4KICAgICAgICAgIDxpZGVudGlmaWNhdGl2b1VuaXZvY29WZXJzYW1lbnRvPjAxMDAwMDAwMDAwMDAwMDIyPC9pZGVudGlmaWNhdGl2b1VuaXZvY29WZXJzYW1lbnRvPgogICAgICAgICAgPGNvZGljZUNvbnRlc3RvUGFnYW1lbnRvPnQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIyPC9jb2RpY2VDb250ZXN0b1BhZ2FtZW50bz4KICAgICAgICAgIDx0aXBvRmlybWEgLz4KICAgICAgICAgIDxycHQ+UEZKUVZDQjRiV3h1Y3owaWFIUjBjRG92TDNkM2R5NWthV2RwZEhCaExtZHZkaTVwZEM5elkyaGxiV0Z6THpJd01URXZVR0ZuWVcxbGJuUnBMeUlnZUcxc2JuTTZlSE5rUFNKb2RIUndPaTh2ZDNkM0xuY3pMbTl5Wnk4eU1EQXhMMWhOVEZOamFHVnRZU0lnZUcxc2JuTTZlSE5wUFNKb2RIUndPaTh2ZDNkM0xuY3pMbTl5Wnk4eU1EQXhMMWhOVEZOamFHVnRZUzFwYm5OMFlXNWpaU0krQ2drOGRtVnljMmx2Ym1WUFoyZGxkSFJ2UGpBOEwzWmxjbk5wYjI1bFQyZG5aWFIwYno0S0NUeGtiMjFwYm1sdlBnb0pDVHhwWkdWdWRHbG1hV05oZEdsMmIwUnZiV2x1YVc4K056YzNOemMzTnpjM056YzhMMmxrWlc1MGFXWnBZMkYwYVhadlJHOXRhVzVwYno0S0NRazhhV1JsYm5ScFptbGpZWFJwZG05VGRHRjZhVzl1WlZKcFkyaHBaV1JsYm5SbFBqYzNOemMzTnpjM056YzNYekF4UEM5cFpHVnVkR2xtYVdOaGRHbDJiMU4wWVhwcGIyNWxVbWxqYUdsbFpHVnVkR1UrQ2drOEwyUnZiV2x1YVc4K0NnazhhV1JsYm5ScFptbGpZWFJwZG05TlpYTnpZV2RuYVc5U2FXTm9hV1Z6ZEdFK05EWTNNREUxTXk0MU1Ed3ZhV1JsYm5ScFptbGpZWFJwZG05TlpYTnpZV2RuYVc5U2FXTm9hV1Z6ZEdFK0NnazhaR0YwWVU5eVlVMWxjM05oWjJkcGIxSnBZMmhwWlhOMFlUNHlNREkwTFRBekxURXpWREl6T2pFME9qSXlQQzlrWVhSaFQzSmhUV1Z6YzJGbloybHZVbWxqYUdsbGMzUmhQZ29KUEdGMWRHVnVkR2xqWVhwcGIyNWxVMjluWjJWMGRHOCtWVk5TUEM5aGRYUmxiblJwWTJGNmFXOXVaVk52WjJkbGRIUnZQZ29KUEhOdloyZGxkSFJ2Vm1WeWMyRnVkR1UrQ2drSlBHbGtaVzUwYVdacFkyRjBhWFp2Vlc1cGRtOWpiMVpsY25OaGJuUmxQZ29KQ1FrOGRHbHdiMGxrWlc1MGFXWnBZMkYwYVhadlZXNXBkbTlqYno1R1BDOTBhWEJ2U1dSbGJuUnBabWxqWVhScGRtOVZibWwyYjJOdlBnb0pDUWs4WTI5a2FXTmxTV1JsYm5ScFptbGpZWFJwZG05VmJtbDJiMk52UG5oNGVIaDRQQzlqYjJScFkyVkpaR1Z1ZEdsbWFXTmhkR2wyYjFWdWFYWnZZMjgrQ2drSlBDOXBaR1Z1ZEdsbWFXTmhkR2wyYjFWdWFYWnZZMjlXWlhKellXNTBaVDRLQ1FrOFlXNWhaM0poWm1sallWWmxjbk5oYm5SbFBuaDRlSGc4TDJGdVlXZHlZV1pwWTJGV1pYSnpZVzUwWlQ0S0NRazhhVzVrYVhKcGVucHZWbVZ5YzJGdWRHVStlSGg0ZUR3dmFXNWthWEpwZW5wdlZtVnljMkZ1ZEdVK0Nna0pQR05wZG1samIxWmxjbk5oYm5SbFBuaDRQQzlqYVhacFkyOVdaWEp6WVc1MFpUNEtDUWs4WTJGd1ZtVnljMkZ1ZEdVK2VIaDRlRHd2WTJGd1ZtVnljMkZ1ZEdVK0Nna0pQR3h2WTJGc2FYUmhWbVZ5YzJGdWRHVStlSGg0ZUhnOEwyeHZZMkZzYVhSaFZtVnljMkZ1ZEdVK0Nna0pQSEJ5YjNacGJtTnBZVlpsY25OaGJuUmxQbmg0ZUhnOEwzQnliM1pwYm1OcFlWWmxjbk5oYm5SbFBnb0pDVHh1WVhwcGIyNWxWbVZ5YzJGdWRHVStTVkk4TDI1aGVtbHZibVZXWlhKellXNTBaVDRLQ1FrOFpTMXRZV2xzVm1WeWMyRnVkR1UrZUhoNGVIaEFaMjFoYVd3dVkyOXRQQzlsTFcxaGFXeFdaWEp6WVc1MFpUNEtDVHd2YzI5bloyVjBkRzlXWlhKellXNTBaVDRLQ1R4emIyZG5aWFIwYjFCaFoyRjBiM0psUGdvSkNUeHBaR1Z1ZEdsbWFXTmhkR2wyYjFWdWFYWnZZMjlRWVdkaGRHOXlaVDRLQ1FrSlBIUnBjRzlKWkdWdWRHbG1hV05oZEdsMmIxVnVhWFp2WTI4K1Jqd3ZkR2x3YjBsa1pXNTBhV1pwWTJGMGFYWnZWVzVwZG05amJ6NEtDUWtKUEdOdlpHbGpaVWxrWlc1MGFXWnBZMkYwYVhadlZXNXBkbTlqYno1NGVIaDRlSGc4TDJOdlpHbGpaVWxrWlc1MGFXWnBZMkYwYVhadlZXNXBkbTlqYno0S0NRazhMMmxrWlc1MGFXWnBZMkYwYVhadlZXNXBkbTlqYjFCaFoyRjBiM0psUGdvSkNUeGhibUZuY21GbWFXTmhVR0ZuWVhSdmNtVStlSGg0ZUhoNFBDOWhibUZuY21GbWFXTmhVR0ZuWVhSdmNtVStDZ2tKUEdsdVpHbHlhWHA2YjFCaFoyRjBiM0psUG5oNGVIZzhMMmx1WkdseWFYcDZiMUJoWjJGMGIzSmxQZ29KQ1R4amFYWnBZMjlRWVdkaGRHOXlaVDU0ZUhoNFBDOWphWFpwWTI5UVlXZGhkRzl5WlQ0S0NRazhZMkZ3VUdGbllYUnZjbVUrZUhoNFBDOWpZWEJRWVdkaGRHOXlaVDRLQ1FrOGJHOWpZV3hwZEdGUVlXZGhkRzl5WlQ1NGVIZzhMMnh2WTJGc2FYUmhVR0ZuWVhSdmNtVStDZ2tKUEc1aGVtbHZibVZRWVdkaGRHOXlaVDU0ZUhoNFBDOXVZWHBwYjI1bFVHRm5ZWFJ2Y21VK0Nna0pQR1V0YldGcGJGQmhaMkYwYjNKbFBuaDRlSGc4TDJVdGJXRnBiRkJoWjJGMGIzSmxQZ29KUEM5emIyZG5aWFIwYjFCaFoyRjBiM0psUGdvSlBHVnVkR1ZDWlc1bFptbGphV0Z5YVc4K0Nna0pQR2xrWlc1MGFXWnBZMkYwYVhadlZXNXBkbTlqYjBKbGJtVm1hV05wWVhKcGJ6NEtDUWtKUEhScGNHOUpaR1Z1ZEdsbWFXTmhkR2wyYjFWdWFYWnZZMjgrUnp3dmRHbHdiMGxrWlc1MGFXWnBZMkYwYVhadlZXNXBkbTlqYno0S0NRa0pQR052WkdsalpVbGtaVzUwYVdacFkyRjBhWFp2Vlc1cGRtOWpiejQzTnpjM056YzNOemMzTnp3dlkyOWthV05sU1dSbGJuUnBabWxqWVhScGRtOVZibWwyYjJOdlBnb0pDVHd2YVdSbGJuUnBabWxqWVhScGRtOVZibWwyYjJOdlFtVnVaV1pwWTJsaGNtbHZQZ29KQ1R4a1pXNXZiV2x1WVhwcGIyNWxRbVZ1WldacFkybGhjbWx2UG5oNGVIaDRlRHd2WkdWdWIyMXBibUY2YVc5dVpVSmxibVZtYVdOcFlYSnBiejRLQ1FrOFkyOWthV05sVlc1cGRFOXdaWEpDWlc1bFptbGphV0Z5YVc4K2VIaDRQQzlqYjJScFkyVlZibWwwVDNCbGNrSmxibVZtYVdOcFlYSnBiejRLQ1FrOFpHVnViMjFWYm1sMFQzQmxja0psYm1WbWFXTnBZWEpwYno1NGVIaDRQQzlrWlc1dmJWVnVhWFJQY0dWeVFtVnVaV1pwWTJsaGNtbHZQZ29KQ1R4cGJtUnBjbWw2ZW05Q1pXNWxabWxqYVdGeWFXOCtlSGg0UEM5cGJtUnBjbWw2ZW05Q1pXNWxabWxqYVdGeWFXOCtDZ2tKUEdOcGRtbGpiMEpsYm1WbWFXTnBZWEpwYno1NGVIZzhMMk5wZG1samIwSmxibVZtYVdOcFlYSnBiejRLQ1FrOFkyRndRbVZ1WldacFkybGhjbWx2UG5oNGVEd3ZZMkZ3UW1WdVpXWnBZMmxoY21sdlBnb0pDVHhzYjJOaGJHbDBZVUpsYm1WbWFXTnBZWEpwYno1NGVEd3ZiRzlqWVd4cGRHRkNaVzVsWm1samFXRnlhVzgrQ2drSlBIQnliM1pwYm1OcFlVSmxibVZtYVdOcFlYSnBiejU0ZUR3dmNISnZkbWx1WTJsaFFtVnVaV1pwWTJsaGNtbHZQZ29KQ1R4dVlYcHBiMjVsUW1WdVpXWnBZMmxoY21sdlBrbFVQQzl1WVhwcGIyNWxRbVZ1WldacFkybGhjbWx2UGdvSlBDOWxiblJsUW1WdVpXWnBZMmxoY21sdlBnb0pQR1JoZEdsV1pYSnpZVzFsYm5SdlBnb0pDVHhrWVhSaFJYTmxZM1Y2YVc5dVpWQmhaMkZ0Wlc1MGJ6NHlNREkwTFRBekxURXpQQzlrWVhSaFJYTmxZM1Y2YVc5dVpWQmhaMkZ0Wlc1MGJ6NEtDUWs4YVcxd2IzSjBiMVJ2ZEdGc1pVUmhWbVZ5YzJGeVpUNHhNREF1TURBOEwybHRjRzl5ZEc5VWIzUmhiR1ZFWVZabGNuTmhjbVUrQ2drSlBIUnBjRzlXWlhKellXMWxiblJ2UGtKQ1ZEd3ZkR2x3YjFabGNuTmhiV1Z1ZEc4K0Nna0pQR2xrWlc1MGFXWnBZMkYwYVhadlZXNXBkbTlqYjFabGNuTmhiV1Z1ZEc4K01ERXdNREF3TURBd01EQXdNREF3TWpJOEwybGtaVzUwYVdacFkyRjBhWFp2Vlc1cGRtOWpiMVpsY25OaGJXVnVkRzgrQ2drSlBHTnZaR2xqWlVOdmJuUmxjM1J2VUdGbllXMWxiblJ2UG5Rd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01ESXlQQzlqYjJScFkyVkRiMjUwWlhOMGIxQmhaMkZ0Wlc1MGJ6NEtDUWs4Wm1seWJXRlNhV05sZG5WMFlUNHdQQzltYVhKdFlWSnBZMlYyZFhSaFBnb0pDVHhrWVhScFUybHVaMjlzYjFabGNuTmhiV1Z1ZEc4K0Nna0pDVHhwYlhCdmNuUnZVMmx1WjI5c2IxWmxjbk5oYldWdWRHOCtNVEF3TGpBd1BDOXBiWEJ2Y25SdlUybHVaMjlzYjFabGNuTmhiV1Z1ZEc4K0Nna0pDVHhwWW1GdVFXTmpjbVZrYVhSdlBrbFVNVGhWTURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01Ud3ZhV0poYmtGalkzSmxaR2wwYno0S0NRa0pQR05oZFhOaGJHVldaWEp6WVcxbGJuUnZQaTlTUmxNdlVrWXlNekF3TURBd01EQXdNREF3TURBd05EWTNNREV4TVM4MU1DNHdNRHd2WTJGMWMyRnNaVlpsY25OaGJXVnVkRzgrQ2drSkNUeGtZWFJwVTNCbFkybG1hV05wVW1selkyOXpjMmx2Ym1VK09TOHdOakF4TVRFelFWQXZQQzlrWVhScFUzQmxZMmxtYVdOcFVtbHpZMjl6YzJsdmJtVStDZ2tKUEM5a1lYUnBVMmx1WjI5c2IxWmxjbk5oYldWdWRHOCtDZ2s4TDJSaGRHbFdaWEp6WVcxbGJuUnZQZ284TDFKUVZEND08L3JwdD4KICAgICAgICA8L2VsZW1lbnRvTGlzdGFSUFQ+CiAgICAgIDwvbGlzdGFSUFQ+CiAgICA8L25vZG9JbnZpYUNhcnJlbGxvUlBUPgogIDwvc29hcDpCb2R5Pgo8L3NvYXA6RW52ZWxvcGU+"
]);


print_r($a->getMethodInterface()->getIuv(0));




die();
$string = 'PHNvYXA6RW52ZWxvcGUgeG1sbnM6c29hcD0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iPgoJPHNvYXA6SGVhZGVyPgoJCTxuczU6aW50ZXN0YXppb25lQ2FycmVsbG9QUFQgc29hcDphY3Rvcj0iIiBzb2FwOm11c3RVbmRlcnN0YW5kPSIxIiB4bWxuczpuczM9Imh0dHA6Ly9Ob2RvUGFnYW1lbnRpU1BDLnNwY29vcC5nb3YuaXQvc2Vydml6aS9QYWdhbWVudGlUZWxlbWF0aWNpUlBUIiB4bWxuczpuczQ9Imh0dHA6Ly93cy5wYWdhbWVudGkudGVsZW1hdGljaS5nb3YvIiB4bWxuczpuczU9Imh0dHA6Ly93cy5wYWdhbWVudGkudGVsZW1hdGljaS5nb3YvcHB0aGVhZCI+CgkJCTxpZGVudGlmaWNhdGl2b0ludGVybWVkaWFyaW9QQT43Nzc3Nzc3Nzc3NzwvaWRlbnRpZmljYXRpdm9JbnRlcm1lZGlhcmlvUEE+CgkJCTxpZGVudGlmaWNhdGl2b1N0YXppb25lSW50ZXJtZWRpYXJpb1BBPjc3Nzc3Nzc3Nzc3XzAxPC9pZGVudGlmaWNhdGl2b1N0YXppb25lSW50ZXJtZWRpYXJpb1BBPgoJCQk8aWRlbnRpZmljYXRpdm9DYXJyZWxsbz5JRF9DQVJSRUxMT18wNTwvaWRlbnRpZmljYXRpdm9DYXJyZWxsbz4KCQk8L25zNTppbnRlc3RhemlvbmVDYXJyZWxsb1BQVD4KCTwvc29hcDpIZWFkZXI+Cgk8c29hcDpCb2R5PgoJCTxuczQ6bm9kb0ludmlhQ2FycmVsbG9SUFQgeG1sbnM6bnMyPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VudmVsb3BlLyIgeG1sbnM6bnMzPSJodHRwOi8vTm9kb1BhZ2FtZW50aVNQQy5zcGNvb3AuZ292Lml0L3NlcnZpemkvUGFnYW1lbnRpVGVsZW1hdGljaVJQVCIgeG1sbnM6bnM0PSJodHRwOi8vd3MucGFnYW1lbnRpLnRlbGVtYXRpY2kuZ292LyI+CgkJCTxwYXNzd29yZD5QTEFDRUhPTERFUjwvcGFzc3dvcmQ+CgkJCTxpZGVudGlmaWNhdGl2b1BTUD5BR0lEXzAxPC9pZGVudGlmaWNhdGl2b1BTUD4KCQkJPGlkZW50aWZpY2F0aXZvSW50ZXJtZWRpYXJpb1BTUD44ODg4ODg4ODg4ODwvaWRlbnRpZmljYXRpdm9JbnRlcm1lZGlhcmlvUFNQPgoJCQk8aWRlbnRpZmljYXRpdm9DYW5hbGU+ODg4ODg4ODg4ODhfMDE8L2lkZW50aWZpY2F0aXZvQ2FuYWxlPgoJCQk8bGlzdGFSUFQ+CgkJCQk8ZWxlbWVudG9MaXN0YVJQVD4KCQkJCQk8aWRlbnRpZmljYXRpdm9Eb21pbmlvPjc3Nzc3Nzc3Nzc3PC9pZGVudGlmaWNhdGl2b0RvbWluaW8+CgkJCQkJPGlkZW50aWZpY2F0aXZvVW5pdm9jb1ZlcnNhbWVudG8+MDEwMDAwMDAwMDAwMDAwMjM8L2lkZW50aWZpY2F0aXZvVW5pdm9jb1ZlcnNhbWVudG8+CgkJCQkJPGNvZGljZUNvbnRlc3RvUGFnYW1lbnRvPnQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIzPC9jb2RpY2VDb250ZXN0b1BhZ2FtZW50bz4KCQkJCQk8cnB0PlBGSlFWQ0I0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTVrYVdkcGRIQmhMbWR2ZGk1cGRDOXpZMmhsYldGekx6SXdNVEV2VUdGbllXMWxiblJwTHlJK0NnazhkbVZ5YzJsdmJtVlBaMmRsZEhSdlBqRXVNRHd2ZG1WeWMybHZibVZQWjJkbGRIUnZQZ29KUEdSdmJXbHVhVzgrQ2drSlBHbGtaVzUwYVdacFkyRjBhWFp2Ukc5dGFXNXBiejQzTnpjM056YzNOemMzTnp3dmFXUmxiblJwWm1sallYUnBkbTlFYjIxcGJtbHZQZ29KUEM5a2IyMXBibWx2UGdvSlBHbGtaVzUwYVdacFkyRjBhWFp2VFdWemMyRm5aMmx2VW1samFHbGxjM1JoUGpJd01qTXhNakUxTURFd01UVXpPV0ZpWW1Fek16VXRZV0kwWlMwMFpERTRMV0V6UEM5cFpHVnVkR2xtYVdOaGRHbDJiMDFsYzNOaFoyZHBiMUpwWTJocFpYTjBZVDRLQ1R4a1lYUmhUM0poVFdWemMyRm5aMmx2VW1samFHbGxjM1JoUGpJd01qTXRNVEl0TVRWVU1UTTZNREU2TlRNdU5qRTVLekF4T2pBd1BDOWtZWFJoVDNKaFRXVnpjMkZuWjJsdlVtbGphR2xsYzNSaFBnb0pQR0YxZEdWdWRHbGpZWHBwYjI1bFUyOW5aMlYwZEc4K1RpOUJQQzloZFhSbGJuUnBZMkY2YVc5dVpWTnZaMmRsZEhSdlBnb0pQSE52WjJkbGRIUnZWbVZ5YzJGdWRHVStDZ2tKUEdsa1pXNTBhV1pwWTJGMGFYWnZWVzVwZG05amIxWmxjbk5oYm5SbFBnb0pDUWs4ZEdsd2IwbGtaVzUwYVdacFkyRjBhWFp2Vlc1cGRtOWpiejVIUEM5MGFYQnZTV1JsYm5ScFptbGpZWFJwZG05VmJtbDJiMk52UGdvSkNRazhZMjlrYVdObFNXUmxiblJwWm1sallYUnBkbTlWYm1sMmIyTnZQamMzTnpjM056YzNOemMzUEM5amIyUnBZMlZKWkdWdWRHbG1hV05oZEdsMmIxVnVhWFp2WTI4K0Nna0pQQzlwWkdWdWRHbG1hV05oZEdsMmIxVnVhWFp2WTI5V1pYSnpZVzUwWlQ0S0NRazhZVzVoWjNKaFptbGpZVlpsY25OaGJuUmxQbmg0ZUhoNFBDOWhibUZuY21GbWFXTmhWbVZ5YzJGdWRHVStDZ2s4TDNOdloyZGxkSFJ2Vm1WeWMyRnVkR1UrQ2drOGMyOW5aMlYwZEc5UVlXZGhkRzl5WlQ0S0NRazhhV1JsYm5ScFptbGpZWFJwZG05VmJtbDJiMk52VUdGbllYUnZjbVUrQ2drSkNUeDBhWEJ2U1dSbGJuUnBabWxqWVhScGRtOVZibWwyYjJOdlBrYzhMM1JwY0c5SlpHVnVkR2xtYVdOaGRHbDJiMVZ1YVhadlkyOCtDZ2tKQ1R4amIyUnBZMlZKWkdWdWRHbG1hV05oZEdsMmIxVnVhWFp2WTI4K056YzNOemMzTnpjM056YzhMMk52WkdsalpVbGtaVzUwYVdacFkyRjBhWFp2Vlc1cGRtOWpiejRLQ1FrOEwybGtaVzUwYVdacFkyRjBhWFp2Vlc1cGRtOWpiMUJoWjJGMGIzSmxQZ29KQ1R4aGJtRm5jbUZtYVdOaFVHRm5ZWFJ2Y21VK2VIaDRlRHd2WVc1aFozSmhabWxqWVZCaFoyRjBiM0psUGdvSlBDOXpiMmRuWlhSMGIxQmhaMkYwYjNKbFBnb0pQR1Z1ZEdWQ1pXNWxabWxqYVdGeWFXOCtDZ2tKUEdsa1pXNTBhV1pwWTJGMGFYWnZWVzVwZG05amIwSmxibVZtYVdOcFlYSnBiejRLQ1FrSlBIUnBjRzlKWkdWdWRHbG1hV05oZEdsMmIxVnVhWFp2WTI4K1J6d3ZkR2x3YjBsa1pXNTBhV1pwWTJGMGFYWnZWVzVwZG05amJ6NEtDUWtKUEdOdlpHbGpaVWxrWlc1MGFXWnBZMkYwYVhadlZXNXBkbTlqYno0M056YzNOemMzTnpjM056d3ZZMjlrYVdObFNXUmxiblJwWm1sallYUnBkbTlWYm1sMmIyTnZQZ29KQ1R3dmFXUmxiblJwWm1sallYUnBkbTlWYm1sMmIyTnZRbVZ1WldacFkybGhjbWx2UGdvSkNUeGtaVzV2YldsdVlYcHBiMjVsUW1WdVpXWnBZMmxoY21sdlBuaDRlSGg0ZUR3dlpHVnViMjFwYm1GNmFXOXVaVUpsYm1WbWFXTnBZWEpwYno0S0NRazhZMjlrYVdObFZXNXBkRTl3WlhKQ1pXNWxabWxqYVdGeWFXOCtSRlE4TDJOdlpHbGpaVlZ1YVhSUGNHVnlRbVZ1WldacFkybGhjbWx2UGdvSkNUeGtaVzV2YlZWdWFYUlBjR1Z5UW1WdVpXWnBZMmxoY21sdlBuaDRlSGg0ZUhnOEwyUmxibTl0Vlc1cGRFOXdaWEpDWlc1bFptbGphV0Z5YVc4K0Nna0pQR2x1WkdseWFYcDZiMEpsYm1WbWFXTnBZWEpwYno1NGVIaDRQQzlwYm1ScGNtbDZlbTlDWlc1bFptbGphV0Z5YVc4K0Nna0pQR05wZG1samIwSmxibVZtYVdOcFlYSnBiejU0ZUR3dlkybDJhV052UW1WdVpXWnBZMmxoY21sdlBnb0pDVHhqWVhCQ1pXNWxabWxqYVdGeWFXOCtlSGg0UEM5allYQkNaVzVsWm1samFXRnlhVzgrQ2drSlBHeHZZMkZzYVhSaFFtVnVaV1pwWTJsaGNtbHZQbmg0ZUR3dmJHOWpZV3hwZEdGQ1pXNWxabWxqYVdGeWFXOCtDZ2tKUEhCeWIzWnBibU5wWVVKbGJtVm1hV05wWVhKcGJ6NTRlRHd2Y0hKdmRtbHVZMmxoUW1WdVpXWnBZMmxoY21sdlBnb0pDVHh1WVhwcGIyNWxRbVZ1WldacFkybGhjbWx2UG5oNFBDOXVZWHBwYjI1bFFtVnVaV1pwWTJsaGNtbHZQZ29KUEM5bGJuUmxRbVZ1WldacFkybGhjbWx2UGdvSlBHUmhkR2xXWlhKellXMWxiblJ2UGdvSkNUeGtZWFJoUlhObFkzVjZhVzl1WlZCaFoyRnRaVzUwYno0eU1ESXpMVEV5TFRFMUt6QXhPakF3UEM5a1lYUmhSWE5sWTNWNmFXOXVaVkJoWjJGdFpXNTBiejRLQ1FrOGFXMXdiM0owYjFSdmRHRnNaVVJoVm1WeWMyRnlaVDQyTVRZdU1EQThMMmx0Y0c5eWRHOVViM1JoYkdWRVlWWmxjbk5oY21VK0Nna0pQSFJwY0c5V1pYSnpZVzFsYm5SdlBrSkNWRHd2ZEdsd2IxWmxjbk5oYldWdWRHOCtDZ2tKUEdsa1pXNTBhV1pwWTJGMGFYWnZWVzVwZG05amIxWmxjbk5oYldWdWRHOCtNREV3TURBd01EQXdNREF3TURBd01qTThMMmxrWlc1MGFXWnBZMkYwYVhadlZXNXBkbTlqYjFabGNuTmhiV1Z1ZEc4K0Nna0pQR052WkdsalpVTnZiblJsYzNSdlVHRm5ZVzFsYm5SdlBuUXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNREl6UEM5amIyUnBZMlZEYjI1MFpYTjBiMUJoWjJGdFpXNTBiejRLQ1FrOFptbHliV0ZTYVdObGRuVjBZVDR3UEM5bWFYSnRZVkpwWTJWMmRYUmhQZ29KQ1R4a1lYUnBVMmx1WjI5c2IxWmxjbk5oYldWdWRHOCtDZ2tKQ1R4cGJYQnZjblJ2VTJsdVoyOXNiMVpsY25OaGJXVnVkRzgrTmpBd0xqQXdQQzlwYlhCdmNuUnZVMmx1WjI5c2IxWmxjbk5oYldWdWRHOCtDZ2tKQ1R4cFltRnVRV05qY21Wa2FYUnZQa2xVTVRoVk1EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNVHd2YVdKaGJrRmpZM0psWkdsMGJ6NEtDUWtKUEdOaGRYTmhiR1ZXWlhKellXMWxiblJ2UGk5U1JrSXZNRFEzTURRNE9EVXdPVEk0TWpJNU1qQXZOalUxTGpBeUwxUllWQzlCVEVKUExWQkJSMEZOUlU1VVR5QlJWVTlVUVNCQlRFSlBJRUZWVkU5VVVrRlRVRTlTVkU4OEwyTmhkWE5oYkdWV1pYSnpZVzFsYm5SdlBnb0pDUWs4WkdGMGFWTndaV05wWm1samFWSnBjMk52YzNOcGIyNWxQamt2TURjeE5URXdORk5RTHp3dlpHRjBhVk53WldOcFptbGphVkpwYzJOdmMzTnBiMjVsUGdvSkNUd3ZaR0YwYVZOcGJtZHZiRzlXWlhKellXMWxiblJ2UGdvSkNUeGtZWFJwVTJsdVoyOXNiMVpsY25OaGJXVnVkRzgrQ2lBZ0lDQWdJQ0FnSUR4cGJYQnZjblJ2VTJsdVoyOXNiMVpsY25OaGJXVnVkRzgrTVRZdU1EQThMMmx0Y0c5eWRHOVRhVzVuYjJ4dlZtVnljMkZ0Wlc1MGJ6NEtJQ0FnSUNBZ0lDQWdQR05oZFhOaGJHVldaWEp6WVcxbGJuUnZQaTlTUmxNdlVrWXdOVEF3TURBd01EQXdNREF3TURBMk56Y3dPRGN6THpFMkxqQXdMMVJZVkM5Q1QweE1UMFJKUjBsVVFVeEZMVUZPVUZKQ0xUSjZSVVZQZVdoRE1qTThMMk5oZFhOaGJHVldaWEp6WVcxbGJuUnZQZ29nSUNBZ0lDQWdJQ0E4WkdGMGFWTndaV05wWm1samFWSnBjMk52YzNOcGIyNWxQamt2TURrd01URXdNRUZRTDBKUFRFeFBMMmRpWjBoZFowUmVSMHBwV1ZCb1VHaEdNakJxZVdJMFExQjJLRDFNT1M5dGJYdGplRTF0TmpjOEwyUmhkR2xUY0dWamFXWnBZMmxTYVhOamIzTnphVzl1WlQ0S0lDQWdJQ0FnSUNBZ1BHUmhkR2xOWVhKallVSnZiR3h2UkdsbmFYUmhiR1UrQ2lBZ0lDQWdJQ0FnSUNBZ0lEeDBhWEJ2UW05c2JHOCtNREU4TDNScGNHOUNiMnhzYno0S0lDQWdJQ0FnSUNBZ0lDQWdQR2hoYzJoRWIyTjFiV1Z1ZEc4K2VIaDRlSGg0UEM5b1lYTm9SRzlqZFcxbGJuUnZQZ29nSUNBZ0lDQWdJQ0FnSUNBOGNISnZkbWx1WTJsaFVtVnphV1JsYm5waFBsSk5QQzl3Y205MmFXNWphV0ZTWlhOcFpHVnVlbUUrQ2lBZ0lDQWdJQ0FnSUR3dlpHRjBhVTFoY21OaFFtOXNiRzlFYVdkcGRHRnNaVDRLSUNBZ0lDQWdJQ0E4TDJSaGRHbFRhVzVuYjJ4dlZtVnljMkZ0Wlc1MGJ6NEtDVHd2WkdGMGFWWmxjbk5oYldWdWRHOCtDand2VWxCVVBnPT08L3JwdD4KCQkJCTwvZWxlbWVudG9MaXN0YVJQVD4KCQkJPC9saXN0YVJQVD4KCQk8L25zNDpub2RvSW52aWFDYXJyZWxsb1JQVD4KCTwvc29hcDpCb2R5Pgo8L3NvYXA6RW52ZWxvcGU+';



$nodo = new \pagopa\crawler\methods\req\nodoInviaCarrelloRPT(base64_decode($string));


$nodo->getTransferPa(0, 0);

echo PHP_EOL;


die();
$memcache = new \Memcached();
$memcache->addServer('172.17.0.3', 11211);

$memcache->append('a', '2');
$memcache->append('a', '3');

$memcache->set('b', 5);

print_r($memcache->get('YXR0ZW1wdF8yMDI0MDMxMF8wMTAwMDAwMDAwMDAwMDAxMV83Nzc3Nzc3Nzc3N190MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMQ=='));




die();

require_once './vendor/autoload.php';

use Illuminate\Database\Capsule\Manager as Capsule;
use pagopa\crawler\events\req\nodoInviaCarrelloRPT;
use pagopa\crawler\Memcached;


const MEMCACHED_HOST = '172.17.0.3';

const MEMCACHED_PORT = "11211";
const DB_HOST = '172.17.0.5';
const DB_PORT = '5432';
const DB_DATABASE = 'postgres';
const DB_USERNAME = 'postgres';
const DB_PASSWORD = 'mock';



$capsule = new Capsule;

$capsule->addConnection([
    'driver' => 'pgsql',
    'host' => DB_HOST,
    'port' => DB_PORT,
    'database' => DB_DATABASE,
    'username' => DB_USERNAME,
    'password' => DB_PASSWORD,
    'charset' => 'utf8',
    'collation' => 'utf8_unicode_ci'
]);

$capsule->setAsGlobal();
$capsule->bootEloquent();
$memcache = new Memcached();

//Capsule::statement('truncate table transaction_2024, transaction_details_2024, transaction_events_2024;');
//Capsule::statement('update transaction_re_2024 set state=:state', [':state' => 'TO_LOAD']);

$a = new \pagopa\crawler\paymentlist\req\activatePaymentNotice(new \DateTime('2024-03-10'),'activatePaymentNotice', 'REQ', $memcache);
$a->run();


$a = new \pagopa\crawler\paymentlist\resp\activatePaymentNotice(new \DateTime('2024-03-10'),'activatePaymentNotice', 'RESP', $memcache);
$a->run();





die();

$payload = '
<soapenv:Envelope xmlns:common="http://pagopa-api.pagopa.gov.it/xsd/common-types/v1.0.0/" xmlns:nfp="http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<soapenv:Body>
		<nfp:activatePaymentNoticeRes>
			<outcome>OK</outcome>
			<totalAmount>183.85</totalAmount>
			<paymentDescription>ENEL ENERGIA/NUMDOC=4355425863/DATADOC=08.08.2023/AVVISO=304100435542586389/IMPORTO=183,85/</paymentDescription>
			<fiscalCodePA>06655971007</fiscalCodePA>
			<companyName>Enel Energia S.p.A.</companyName>
			<paymentToken>0a8ef4f0194f4886942cbc8da8fdbe04</paymentToken>
			<transferList>
				<transfer>
					<idTransfer>1</idTransfer>
					<transferAmount>183.85</transferAmount>
					<fiscalCodePA>06655971007</fiscalCodePA>
					<IBAN>IT18U0306909400100000009138</IBAN>
					<remittanceInformation>/RFB/04100435542586389/TXT/ENEL ENERGIA/NUMDOC=4355425863/DATADOC=08.08.2023/AVVISO=304100435542586389/IMPORTO=183,85/</remittanceInformation>
				</transfer>
			</transferList>
			<creditorReferenceId>04100435542586389</creditorReferenceId>
		</nfp:activatePaymentNoticeRes>
	</soapenv:Body>
</soapenv:Envelope>';


$xml = new XMLReader();
$xml->XML($payload);
while($xml->read())
{
    if (($xml->nodeType == XMLReader::ELEMENT) && ($xml->localName == 'transferList'))
    {
        echo $xml->readOuterXml();
    }
}


die();

require_once './vendor/autoload.php';


const MEMCACHED_HOST    =   '172.21.0.3';
const MEMCACHED_PORT    =   11211;


$memcached = new Memcached();
$memcached->addServer(MEMCACHED_HOST,MEMCACHED_PORT);


print_r($memcached->getStats());






die();
$instance = new \pagopa\crawler\SingleRow('test_table');
$r = new ReflectionClass($instance);

$property = $r->getProperty('primary_keys');
$property->setValue($instance, ['pk_need']);

print_r($instance->getPrimaryKeys());








die();
const MEMCACHED_HOST    =   '172.21.0.4';
const MEMCACHED_PORT    =   11211;


$memcached = new Memcached();
$memcached->addServer(MEMCACHED_HOST,MEMCACHED_PORT);

$data = [
    'prima chiave'
];

$memcached->set('test_chiave', $data, (time() + 5));

sleep(3);

print_r($memcached->get('test_chiave'));

echo PHP_EOL;
echo "adesso aggiorno la chiave e metto altri 5 secondi";
$data[] = 'seconda chiave';
$memcached->set('test_chiave', $data, (time() + 5));
echo PHP_EOL;
sleep(3);

print_r($memcached->get('test_chiave'));








die();

$a = [
    'ch' => 5,
    'cp' => 6
];

$b = (object) $a;

echo $b->ch;
echo PHP_EOL;
echo $b->cp;
echo PHP_EOL;




die();
$f1 = false;
$f2 = false;

$a = 4;
$t1 = 6;


$b = 5;
$t2 = 6;


if (($f1 = ($a == $t1)) || ($f2 = ($b == $t2)))
{
    echo "IO QUI CI ENTRO SEMPRE" .PHP_EOL;
}


echo $a ." == " .$t1 ." , f1 => " .var_dump($f1);
echo PHP_EOL;
echo $b ." == " .$t2 ." , f2 => " .var_dump($f2);
echo PHP_EOL;

// nel ciclo ci entro solo se una delle due è vera
// se entro, e $f1 è true, allora è vera la prima condizione
// else, sicuramente è vera la seconda, altrimenti nel ciclo non entravo proprio
// quindi posso usare $f1 per capire quale delle due condizioni mi ha fatto entrare nel blocco


die();


$date = '2023-03-30';
$c = new DateTime($date);
$m = $c->format('m');
$d = $c->format('d');
$step = new DateInterval('P1D');

if ($d < 29)
{
    $c->setDate($c->format('Y'), $c->format('m'), 28);
}

while($m == $c->format('m'))
{
    $c->add($step);
}

echo $c->format('Y-m-d') .PHP_EOL;
$c->sub($step);
echo $c->format('Y-m-d');